# version: "2.3"

name: whispergrid

services:
  whispergrid-server:
    build:
      dockerfile: whispergrid.Dockerfile
      context: .
    network_mode: service:ts-whispergrid
    # volumes:
    #   - tailscale-data:/data
    environment:
      - PORT=1234
    env_file:
      - path: ./local.env
        required: true
  ts-whispergrid:
    build:
      context: .
      dockerfile_inline: |
        FROM tailscale/tailscale:latest
        COPY ts-certs.sh .
        ENTRYPOINT ["./ts-certs.sh"]
    env_file:
      - path: ./ts.env
        required: true
      - path: ./local.env
        required: false
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  ntfy-service:
    env_file:
      - path: ./local.env
        required: true
    build:
      context: .
      dockerfile_inline: |
        FROM binwiederhier/ntfy
        COPY server.yml /etc/ntfy/server.yml
        RUN echo "base-url: https://$CERT_DOMAIN:4433/" >> /etc/ntfy/server.yml
      args:
        - CERT_DOMAIN
    network_mode: service:ts-whispergrid
    depends_on:
      - ts-whispergrid
    command:
      - serve
    environment:
      - TZ=PST
    volumes:
      - tailscale-data:/var/lib/tailscale
      - ntfy:/etc/ntfy
      - ./server.yml:/etc/ntfy/server.yml

    healthcheck: # optional: remember to adapt the host:port to your environment
      test:
        [
          "CMD-SHELL",
          "wget -q --tries=1 https://$${ CERT_DOMAIN }/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1",
        ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  ntfy:
    driver: local
  tailscale-data:
    driver: local
