/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Invite
 */
export interface Invite {
  /**
   *
   * @type {string}
   * @memberof Invite
   */
  invite: string;
}

/**
 * Check if a given object implements the Invite interface.
 */
export function instanceOfInvite(value: object): value is Invite {
  if (!("invite" in value) || value["invite"] === undefined) return false;
  return true;
}

export function InviteFromJSON(json: any): Invite {
  return InviteFromJSONTyped(json, false);
}

export function InviteFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Invite {
  if (json == null) {
    return json;
  }
  return {
    invite: json["invite"],
  };
}

export function InviteToJSON(value?: Invite | null): any {
  if (value == null) {
    return value;
  }
  return {
    invite: value["invite"],
  };
}
