/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface UploadBackupRequest
 */
export interface UploadBackupRequest {
  /**
   *
   * @type {string}
   * @memberof UploadBackupRequest
   */
  signedBackup: string;
  /**
   *
   * @type {string}
   * @memberof UploadBackupRequest
   */
  thumbprint: string;
}

/**
 * Check if a given object implements the UploadBackupRequest interface.
 */
export function instanceOfUploadBackupRequest(
  value: object,
): value is UploadBackupRequest {
  if (!("signedBackup" in value) || value["signedBackup"] === undefined)
    return false;
  if (!("thumbprint" in value) || value["thumbprint"] === undefined)
    return false;
  return true;
}

export function UploadBackupRequestFromJSON(json: any): UploadBackupRequest {
  return UploadBackupRequestFromJSONTyped(json, false);
}

export function UploadBackupRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UploadBackupRequest {
  if (json == null) {
    return json;
  }
  return {
    signedBackup: json["signedBackup"],
    thumbprint: json["thumbprint"],
  };
}

export function UploadBackupRequestToJSON(
  value?: UploadBackupRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {
    signedBackup: value["signedBackup"],
    thumbprint: value["thumbprint"],
  };
}
