"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfInvite = instanceOfInvite;
exports.InviteFromJSON = InviteFromJSON;
exports.InviteFromJSONTyped = InviteFromJSONTyped;
exports.InviteToJSON = InviteToJSON;
/**
 * Check if a given object implements the Invite interface.
 */
function instanceOfInvite(value) {
    if (!("invite" in value) || value["invite"] === undefined)
        return false;
    return true;
}
function InviteFromJSON(json) {
    return InviteFromJSONTyped(json, false);
}
function InviteFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        invite: json["invite"],
    };
}
function InviteToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        invite: value["invite"],
    };
}
