"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfLoginRequest = instanceOfLoginRequest;
exports.LoginRequestFromJSON = LoginRequestFromJSON;
exports.LoginRequestFromJSONTyped = LoginRequestFromJSONTyped;
exports.LoginRequestToJSON = LoginRequestToJSON;
/**
 * Check if a given object implements the LoginRequest interface.
 */
function instanceOfLoginRequest(value) {
    if (!("signedChallenge" in value) || value["signedChallenge"] === undefined)
        return false;
    return true;
}
function LoginRequestFromJSON(json) {
    return LoginRequestFromJSONTyped(json, false);
}
function LoginRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        signedChallenge: json["signedChallenge"],
    };
}
function LoginRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        signedChallenge: value["signedChallenge"],
    };
}
