"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPublishReplyRequest = instanceOfPublishReplyRequest;
exports.PublishReplyRequestFromJSON = PublishReplyRequestFromJSON;
exports.PublishReplyRequestFromJSONTyped = PublishReplyRequestFromJSONTyped;
exports.PublishReplyRequestToJSON = PublishReplyRequestToJSON;
/**
 * Check if a given object implements the PublishReplyRequest interface.
 */
function instanceOfPublishReplyRequest(value) {
    if (!("signedReply" in value) || value["signedReply"] === undefined)
        return false;
    return true;
}
function PublishReplyRequestFromJSON(json) {
    return PublishReplyRequestFromJSONTyped(json, false);
}
function PublishReplyRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        signedReply: json["signedReply"],
    };
}
function PublishReplyRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        signedReply: value["signedReply"],
    };
}
