"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfReplyToInvite200Response = instanceOfReplyToInvite200Response;
exports.ReplyToInvite200ResponseFromJSON = ReplyToInvite200ResponseFromJSON;
exports.ReplyToInvite200ResponseFromJSONTyped = ReplyToInvite200ResponseFromJSONTyped;
exports.ReplyToInvite200ResponseToJSON = ReplyToInvite200ResponseToJSON;
/**
 * Check if a given object implements the ReplyToInvite200Response interface.
 */
function instanceOfReplyToInvite200Response(value) {
    if (!("threadId" in value) || value["threadId"] === undefined)
        return false;
    return true;
}
function ReplyToInvite200ResponseFromJSON(json) {
    return ReplyToInvite200ResponseFromJSONTyped(json, false);
}
function ReplyToInvite200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        threadId: json["threadId"],
    };
}
function ReplyToInvite200ResponseToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        threadId: value["threadId"],
    };
}
