"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfReplyToInvite = instanceOfReplyToInvite;
exports.ReplyToInviteFromJSON = ReplyToInviteFromJSON;
exports.ReplyToInviteFromJSONTyped = ReplyToInviteFromJSONTyped;
exports.ReplyToInviteToJSON = ReplyToInviteToJSON;
/**
 * Check if a given object implements the ReplyToInvite interface.
 */
function instanceOfReplyToInvite(value) {
    if (!("replyToInvite" in value) || value["replyToInvite"] === undefined)
        return false;
    return true;
}
function ReplyToInviteFromJSON(json) {
    return ReplyToInviteFromJSONTyped(json, false);
}
function ReplyToInviteFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        replyToInvite: json["ReplyToInvite"],
    };
}
function ReplyToInviteToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        ReplyToInvite: value["replyToInvite"],
    };
}
