"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfUploadBackupRequest = instanceOfUploadBackupRequest;
exports.UploadBackupRequestFromJSON = UploadBackupRequestFromJSON;
exports.UploadBackupRequestFromJSONTyped = UploadBackupRequestFromJSONTyped;
exports.UploadBackupRequestToJSON = UploadBackupRequestToJSON;
/**
 * Check if a given object implements the UploadBackupRequest interface.
 */
function instanceOfUploadBackupRequest(value) {
    if (!("signedBackup" in value) || value["signedBackup"] === undefined)
        return false;
    if (!("thumbprint" in value) || value["thumbprint"] === undefined)
        return false;
    return true;
}
function UploadBackupRequestFromJSON(json) {
    return UploadBackupRequestFromJSONTyped(json, false);
}
function UploadBackupRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        signedBackup: json["signedBackup"],
        thumbprint: json["thumbprint"],
    };
}
function UploadBackupRequestToJSON(value) {
    if (value == null) {
        return value;
    }
    return {
        signedBackup: value["signedBackup"],
        thumbprint: value["thumbprint"],
    };
}
