/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishReplyRequest
 */
export interface PublishReplyRequest {
    /**
     * 
     * @type {string}
     * @memberof PublishReplyRequest
     */
    signedReply: string;
}

/**
 * Check if a given object implements the PublishReplyRequest interface.
 */
export function instanceOfPublishReplyRequest(value: object): value is PublishReplyRequest {
    if (!('signedReply' in value) || value['signedReply'] === undefined) return false;
    return true;
}

export function PublishReplyRequestFromJSON(json: any): PublishReplyRequest {
    return PublishReplyRequestFromJSONTyped(json, false);
}

export function PublishReplyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishReplyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'signedReply': json['signedReply'],
    };
}

export function PublishReplyRequestToJSON(value?: PublishReplyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'signedReply': value['signedReply'],
    };
}

