/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublishInviteRequest
 */
export interface PublishInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof PublishInviteRequest
     */
    invite: string;
}

/**
 * Check if a given object implements the PublishInviteRequest interface.
 */
export function instanceOfPublishInviteRequest(value: object): value is PublishInviteRequest {
    if (!('invite' in value) || value['invite'] === undefined) return false;
    return true;
}

export function PublishInviteRequestFromJSON(json: any): PublishInviteRequest {
    return PublishInviteRequestFromJSONTyped(json, false);
}

export function PublishInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishInviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invite': json['invite'],
    };
}

export function PublishInviteRequestToJSON(value?: PublishInviteRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invite': value['invite'],
    };
}

