/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI WhisperGrid
 * OpenAPI definition for WhisperGrid relays.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplyToInvite200Response
 */
export interface ReplyToInvite200Response {
    /**
     * 
     * @type {string}
     * @memberof ReplyToInvite200Response
     */
    threadId: string;
}

/**
 * Check if a given object implements the ReplyToInvite200Response interface.
 */
export function instanceOfReplyToInvite200Response(value: object): value is ReplyToInvite200Response {
    if (!('threadId' in value) || value['threadId'] === undefined) return false;
    return true;
}

export function ReplyToInvite200ResponseFromJSON(json: any): ReplyToInvite200Response {
    return ReplyToInvite200ResponseFromJSONTyped(json, false);
}

export function ReplyToInvite200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplyToInvite200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'threadId': json['threadId'],
    };
}

export function ReplyToInvite200ResponseToJSON(value?: ReplyToInvite200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'threadId': value['threadId'],
    };
}

